services:
  kafka:
    image: bitnami/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  mariadb:
    image: mariadb:10
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: dev
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: dev
#  postgres:
#    image: postgres:alpine
#    ports:
#      - "15432:5432"
#    environment:
#      POSTGRES_DB: dev
#      POSTGRES_USER: dev
#      POSTGRES_PASSWORD: dev
