services:
  mariadb:
    image: mariadb:10
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: dev
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: dev
