services:
  kafka:
    image: bitnami/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"

  mariadb:
    image: mariadb:10
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: dev
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_ROOT_PASSWORD: dev
#  postgres:
#    image: postgres:alpine
#    ports:
#      - "15432:5432"
#    environment:
#      POSTGRES_DB: dev
#      POSTGRES_USER: dev
#      POSTGRES_PASSWORD: dev
