spring:
  docker:
    compose:
      file: ./dev-compose.yml

app:
  rest:
    uri: http://localhost:9000/bwhc/etl/api
  kafka:
    topic: test
    response-topic: test-response
    servers: kafka:9092

server:
  port: 8000

