spring:
  docker:
    compose:
      file: ./dev-compose.yml

app:
  #rest:
  #  uri: http://localhost:9000/bwhc/etl/api
  kafka:
    topic: test
    response-topic: test_response
    servers: localhost:9094

server:
  port: 8000

