spring:
  docker:
    compose:
      file: ./dev-compose.yml

app:
  rest:
    uri: http://localhost:9000/bwhc/etl/api/MTBFile
  #kafka:
  #  topic: test
  #  servers: kafka:9092

server:
  port: 8000

