

services:
  dnpm-etl-processor:
    image: dnpm-elt-processor:latest
    env_file:
      - ./env-sample.env
    depends_on:
      - db
    networks:
      - dnpm_processor
    ports:
      - "${MONITORING_HTTP_PORT:-8080}:8080"

  db:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PW}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PW}
    ports:
      - "3306:3306"
    networks:
      - dnpm_processor
networks:
  dnpm_processor: {}
