

services:
  dnpm-etl-processor:
    image: ghcr.io/ccc-mf/etl-processor:latest
    environment:
      SPRING_KAFKA_SECURITY_PROTOCOL: ${SPRING_KAFKA_SECURITY_PROTOCOL}
      SPRING_KAFKA_SSL_TRUST-STORE-TYPE: ${SPRING_KAFKA_SSL_TRUST_STORE_TYPE}
      SPRING_KAFKA_SSL_TRUST-STORE-LOCATION: ${SPRING_KAFKA_SSL_TRUST_STORE_LOCATION}
      SPRING_KAFKA_SSL_TRUST-STORE-PASSWORD: ${SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD}
      SPRING_KAFKA_SSL_KEY-STORE-TYPE: ${SPRING_KAFKA_SSL_KEY_STORE_TYPE}
      SPRING_KAFKA_SSL_KEY-STORE-LOCATION: ${KAFKA_KEY_STORE_LOCATION}
      SPRING_KAFKA_SSL_KEY-STORE-PASSWORD: ${DNPM_PROCESSOR_KEY_STORE_PASSWORD}
      SPRING_KAFKA_PRODUCER_COMPRESSION-TYPE: ${SPRING_KAFKA_PRODUCER_COMPRESSION_TYPE}
      APP_KAFKA_TOPIC: ${APP_KAFKA_TOPIC}
      APP_KAFKA_SERVERS: ${APP_KAFKA_SERVERS}
      APP_KAFKA_GROUP_ID: ${APP_KAFKA_GROUP_ID}
      APP_KAFKA_RESPONSE_TOPIC: ${APP_KAFKA_RESPONSE_TOPIC}
      APP_REST_URI: ${APP_REST_URI}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      APP_PSEUDONYMIZE_GPAS_SSLCALOCATION: ${APP_PSEUDONYMIZE_GPAS_SSLCALOCATION}
      APP_PSEUDONYMIZE_GPAS_PASSWORD: ${APP_PSEUDONYMIZE_GPAS_PASSWORD}
      APP_PSEUDONYMIZE_GPAS_USERNAME: ${APP_PSEUDONYMIZE_GPAS_USERNAME}
      APP_PSEUDONYMIZE_GPAS_TARGET: ${APP_PSEUDONYMIZE_GPAS_TARGET}
      APP_PSEUDONYMIZE_GPAS_URI: ${APP_PSEUDONYMIZE_GPAS_URI}
      APP_PSEUDONYMIZE_PREFIX: ${APP_PSEUDONYMIZE_PREFIX}
      APP_PSEUDONYMIZE_GENERATOR: ${APP_PSEUDONYMIZE_GENERATOR}

    depends_on:
      - db
    ports:
      - "${MONITORING_HTTP_PORT:-8080}:8080"

  db:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PW}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PW}
    ports:
      - "3306:3306"

