name: "Run docker build and deploy"

on:
  push:
    tags: [ '*' ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute image build and push
        run: |
          ./gradlew bootBuildImage
          docker tag ghcr.io/ccc-mf/etl-processor ghcr.io/ccc-mf/etl-processor:${{ github.ref_name }}
          docker push ghcr.io/ccc-mf/etl-processor
          docker push ghcr.io/ccc-mf/etl-processor:${{ github.ref_name }}